framework:
    messenger:
        # Configure le transport des messages échoués
        failure_transport: failed

        transports:
            # Transport asynchrone
            async: 
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    use_notify: true
                    check_delayed_interval: 60000
                retry_strategy:
                    max_retries: 3
                    multiplier: 2

            # Transport pour les messages échoués
            failed: 'doctrine://default?queue_name=failed'

            # Transport synchrone
            sync: 'sync://'

        routing:
            # Les messages spécifiques sont routés vers le transport "sync"
            Symfony\Component\Mailer\Messenger\SendEmailMessage: sync
            Symfony\Component\Notifier\Message\ChatMessage: sync
            Symfony\Component\Notifier\Message\SmsMessage: sync

            # Routez vos messages personnalisés vers "async"
            # 'App\Message\YourMessage': async
